package flow.subflow.ExistUser;

/**
 * This servlet is used to forward the request to the entry point of a
 * project callflow (subflow).
 * Last generated by Orchestration Designer at: 2023-JAN-03  10:56:15 AM
 */
public class bookSelectionByCategory extends com.avaya.sce.runtime.Subflow {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2023-JAN-03  10:56:15 AM
	 */
	public bookSelectionByCategory() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the name of the subflow that is being invoked.  This name is used for
	 * determining the URL mapping for the the entry point of the subflow..
	 *
	 * @return the name of the subflow
	 * Last generated by Orchestration Designer at: 2023-FEB-10  01:16:40 PM
	 */
	protected String getSubflowName() {
		return("BookSelectionByCategory");
	}
	/**
	 * Returns the name of the mapping of sub flow exit points to the URL mappings
	 * of the servlets to return back to in the calling flow.
	 *
	 * @return map of sub flow exit points to servlets in the calling flow.
	 * Last generated by Orchestration Designer at: 2023-FEB-10  01:16:40 PM
	 */
	protected java.util.Map<String,String> getExitPoints() {
		java.util.Map<String, String> exitPoints;
		exitPoints = new java.util.HashMap<String, String>();
		exitPoints.put("BookSelectionByCategory-ReturnTocart", "ExistUser-bookAddData");
		exitPoints.put("BookSelectionByCategory-EventReturn", "ExistUser-ReturnToEvent");
		return exitPoints;
	}
}
