package flow.subflow.ExistUser;

/**
 * This servlet is used to forward the request to the entry point of a
 * project callflow (subflow).
 * Last generated by Orchestration Designer at: 2023-JAN-05  10:44:58 AM
 */
public class CartFlow extends com.avaya.sce.runtime.Subflow {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2023-JAN-05  10:44:58 AM
	 */
	public CartFlow() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the name of the subflow that is being invoked.  This name is used for
	 * determining the URL mapping for the the entry point of the subflow..
	 *
	 * @return the name of the subflow
	 * Last generated by Orchestration Designer at: 2023-FEB-09  02:33:21 PM
	 */
	protected String getSubflowName() {
		return("CartMenuFlow");
	}
	/**
	 * Returns the name of the mapping of sub flow exit points to the URL mappings
	 * of the servlets to return back to in the calling flow.
	 *
	 * @return map of sub flow exit points to servlets in the calling flow.
	 * Last generated by Orchestration Designer at: 2023-FEB-09  02:33:21 PM
	 */
	protected java.util.Map<String,String> getExitPoints() {
		java.util.Map<String, String> exitPoints;
		exitPoints = new java.util.HashMap<String, String>();
		exitPoints.put("CartMenuFlow-returnToSelection", "ExistUser-CategoryMenu");
		exitPoints.put("CartMenuFlow-ReturnToEvent", "ExistUser-ReturnToEvent");
		exitPoints.put("CartMenuFlow-ReturnToExit", "ExistUser-ReturnToExit");
		return exitPoints;
	}
}
