package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2022-DEC-07  11:17:38 AM
 */
public class eLibrary extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(46);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: welcome
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "welcome", "Welcome.wav", "Welcome to E library management system"); 

		// phrase: noInput
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "noInput", "NoInput.wav", "You are not Enter any number"); 

		// phrase: noMatch
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "noMatch", "NoMatch.wav", "Your input is not valid"); 

		// phrase: end
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "end", "endThank.wav", "Thank you for calling E library management System"); 

		// phrase: tam
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "tam", "tamil.wav", "You are select tamil"); 

		// phrase: eng
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "eng", "english.wav", "You are select English"); 

		// phrase: hin
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "hin", "hindi.wav", "You are select hindi"); 

		// phrase: langMenu
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "langMenu", "languageMenu.wav", "welcome to language menu\r\npress 1 for select tamil\r\npress 2 for select English\r\npress 3 for select hindi"); 

		// phrase: langReturn
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "langReturn", "languageReturn.wav", "if You want to continue press 1 \r\nif you want to go back to language menu press 0"); 

		// phrase: userMenu
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "userMenu", "userMenu.wav", "Welcome to user menu\r\nif   you   are   a new user \r\npress 1\r\nif   you   are  existing user \r\npress 2"); 

		// phrase: userReturn
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "userReturn", "userReturn.wav", "if You want to continue press 1 \r\nif you want to go back to user menu press 0"); 

		// phrase: newUser
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "newUser", "newUser.wav", "You are select new user"); 

		// phrase: oldUser
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "oldUser", "oldUser.wav", "You are select Existing user"); 

		// phrase: agentConnect
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "agentConnect", "agentConnect.wav", "You are connecting to Agent"); 

		// phrase: userName
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "userName", "userName.wav", "Enter Your User Id"); 

		// phrase: password
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "password", "userPass.wav", "Enter Your Password"); 

		// phrase: selectMenu
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "selectMenu", "selectionMenu.wav", "Welcome to selection menu"); 

		// phrase: bookSelect
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "bookSelect", "bookSelect.wav", "You are select book menu"); 

		// phrase: authorSelect
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "authorSelect", "authorSelect.wav", "You are select Author menu"); 

		// phrase: bookMenu
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "bookMenu", "bookMenu.wav", "Welcome to book menu\r\n\r\npress 1 for rent Whereabouts book\r\n\r\npress 2 for rent Right Under Our Nose book\r\n\r\npress 3 for rent Unfinished book\r\n\r\npress 4 for rent Mapping Love book\r\n\r\npress 5 for rent The Lost Soul book"); 

		// phrase: authorMenu
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "authorMenu", "authorMenu.wav", "Welcome to Author menu\r\n\r\npress 1 for rent Jhumpa Lahiri books\r\n\r\npress 2 for rent R. Giridharan books\r\n\r\npress 3 for rent Priyanka Chopra Jonas books\r\n\r\npress 4 for rent Ashwiny AIyer Tiwari books\r\n\r\npress 5 for rent Olga Tokarczuk books"); 

		// phrase: bookMenuReturn
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "bookMenuReturn", "bookmenuReturn.wav", "if you want to go to book menu press 1\r\nif you want to exit press 0"); 

		// phrase: authorMenuReturn
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "authorMenuReturn", "authorMenuReturn.wav", "if you want to continue press 1\r\nif you want to go to author menu press 2\r\nif you want to exit press 0"); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2022-DEC-09  11:12:45 AM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(eLibrary.PHRASE_MAP, phraseName));
	}
}
