package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2023-JAN-02  07:31:19 PM
 */
public class Category extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(18);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: Adventure
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "Adventure", "Adventure.wav", "You are select Adventure Category"); 

		// phrase: Classics
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "Classics", "Classics.wav", "You are select Classics Category"); 

		// phrase: Youngadultfiction
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "Youngadultfiction", "Youngadultfiction.wav", "You are select Young adult fiction Category"); 

		// phrase: CategoryMenu
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "CategoryMenu", "CategoryMenu.wav", "Welcome to Category menu"); 

		// phrase: Categoryofbooks
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "Categoryofbooks", "Categoryofbooks.wav", "press 1 for Adventure Category\r\n\r\npress 2 for Classics Category\r\n\r\npress 3 for Young adult fiction Category"); 

		// phrase: Categorymenureturn
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "Categorymenureturn", "Categorymenureturn.wav", "if You want to continue press 1 \r\nif you want to go back to Category menu press 0"); 

		// phrase: AdventureBooks
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "AdventureBooks", "AdventureBooks.wav", "press 1 for select The Little Prince book\r\n\r\npress 2 for select A History of Adventure book"); 

		// phrase: ClassicsBooks
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ClassicsBooks", "ClassicsBooks.wav", "press 1 for select A Tale Of Two Cities book\r\n\r\npress 2 for select Dream Of The Red Chamber book\r\n\r\npress 3 for select The Catcher in the Rye book"); 

		// phrase: YoungadultfictionBooks
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "YoungadultfictionBooks", "YoungadultfictionBooks.wav", "press 1 for select Harry Potter and the Philosophers Stone book\r\n\r\npress 2 for select Harry Potter and the Chamber of Secrets book\r\n\r\npress 3 for select Harry Potter and the Prisoner of Azkaban book"); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-FEB-10  10:02:01 AM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(Category.PHRASE_MAP, phraseName));
	}
}
