package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2022-DEC-07  11:17:38 AM
 */
public class eLibrary extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(88);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: welcome
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "welcome", "Welcome.wav", "Welcome to E library management system"); 

		// phrase: noInput
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "noInput", "NoInput.wav", "You are not Enter any number"); 

		// phrase: noMatch
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "noMatch", "NoMatch.wav", "Your input is not valid"); 

		// phrase: end
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "end", "endThank.wav", "Thank you for calling E library management System"); 

		// phrase: tam
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "tam", "tamil.wav", "You are select tamil"); 

		// phrase: eng
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "eng", "english.wav", "You are select English"); 

		// phrase: hin
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "hin", "hindi.wav", "You are select hindi"); 

		// phrase: langMenu
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "langMenu", "languageMenu.wav", "welcome to language menu"); 

		// phrase: langReturn
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "langReturn", "languageReturn.wav", "if You want to continue press 1 \r\nif you want to go back to language menu press 0"); 

		// phrase: userMenu
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "userMenu", "userMenu.wav", "Welcome to user menu\r\nif   you   are   a new user \r\npress 1\r\nif   you   are  existing user \r\npress 2\r\nif you want to go back to language menu \r\npress 0"); 

		// phrase: userReturn
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "userReturn", "userReturn.wav", "if You want to continue press 1 \r\nif you want to go back to user menu press 0"); 

		// phrase: newUser
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "newUser", "newUser.wav", "You are select new user"); 

		// phrase: oldUser
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "oldUser", "oldUser.wav", "You are select Existing user"); 

		// phrase: agentConnect
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "agentConnect", "agentConnect.wav", "You are connecting to Agent"); 

		// phrase: userName
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "userName", "userName.wav", "Enter Your User Id"); 

		// phrase: password
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "password", "userPass.wav", "Enter Your Password"); 

		// phrase: selectMenu
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "selectMenu", "selectionMenu.wav", "Welcome to selection menu\r\npress 1 for select book by Category\r\npress 2 for select book by author"); 

		// phrase: bookSelect
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "bookSelect", "bookSelect.wav", "You are select book menu"); 

		// phrase: authorSelect
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "authorSelect", "authorSelect.wav", "You are select Author menu"); 

		// phrase: bookMenu
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "bookMenu", "bookMenu.wav", "Welcome to book menu\r\n\r\npress 1 for rent Whereabouts book\r\n\r\npress 2 for rent Right Under Our Nose book\r\n\r\npress 3 for rent Unfinished book\r\n\r\npress 4 for rent Mapping Love book\r\n\r\npress 5 for rent The Lost Soul book"); 

		// phrase: authorMenu
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "authorMenu", "authorMenu.wav", "Welcome to Author menu\r\n\r\npress 1 for rent Jhumpa Lahiri books\r\n\r\npress 2 for rent R. Giridharan books\r\n\r\npress 3 for rent Priyanka Chopra Jonas books\r\n\r\npress 4 for rent Ashwiny AIyer Tiwari books\r\n\r\npress 5 for rent Olga Tokarczuk books"); 

		// phrase: bookMenuReturn
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "bookMenuReturn", "bookmenuReturn.wav", "if you want to go to book menu press 1\r\nif you want to exit press 0"); 

		// phrase: badFetch
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "badFetch", "badfetch.wav", "bad fetch error problem"); 

		// phrase: agentCallEnd
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "agentCallEnd", "AgentCallEnd.wav", ""); 

		// phrase: music
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "music", "Vodafone.wav", ""); 

		// phrase: welcomeJoin
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "welcomeJoin", "welcomeJoin.wav", "We are happy to help you"); 

		// phrase: dataMismatch
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "dataMismatch", "DataMisMatch.wav", "Sorry You are Enter Too many Wrong Inputs"); 

		// phrase: userIdMismatch
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "userIdMismatch", "UserIdMismatch.wav", "Invalid User Id"); 

		// phrase: passwordMismatch
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "passwordMismatch", "PasswordMismatch.wav", "Invalid Password"); 

		// phrase: WhereaboutsBook
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "WhereaboutsBook", "WhereaboutsBook.wav", "You are select Whereabouts book"); 

		// phrase: RightUnderOurNoseBook
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "RightUnderOurNoseBook", "RightUnderOurNoseBook.wav", "you are select Right Under Our Nose book"); 

		// phrase:  UnfinishedBook
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, " UnfinishedBook", "Unfinishedbook.wav", "you are select  Unfinished book"); 

		// phrase: MappingLovebook
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "MappingLovebook", "MappingLovebook.wav", "you are select Mapping Love book"); 

		// phrase: TheLostSoulBook
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "TheLostSoulBook", "TheLostSoulbook.wav", "you are select The Lost Soul book"); 

		// phrase: JhumpaLahiriAuthor
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "JhumpaLahiriAuthor", "JhumpaLahiriAuthor.wav", "You are select Jhumpa Lahiri books"); 

		// phrase: R.GiridharanAuthor
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "R.GiridharanAuthor", "GiridharanAuthor.wav", "You are select R. Giridharan books"); 

		// phrase: PriyankaChopraJonasAuthor
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "PriyankaChopraJonasAuthor", "PriyankaChopraJonasAuthor.wav", "You are select Priyanka Chopra Jonas books"); 

		// phrase: AshwinyAIyerTiwariAuthor
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "AshwinyAIyerTiwariAuthor", "AshwinyAIyerTiwariAuthor.wav", "You are select Ashwiny AIyer Tiwari books"); 

		// phrase: OlgaTokarczukAuthor
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "OlgaTokarczukAuthor", "OlgaTokarczukAuthor.wav", "You are select Olga Tokarczuk books"); 

		// phrase: CategorySelect
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "CategorySelect", "CategorySelect.wav", "You are select Category menu"); 

		// phrase: selectionMenuReturn
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "selectionMenuReturn", "selectionMenuReturn.wav", "if You want to continue press 1 \r\nif you want to go back to selection menu press 0"); 

		// phrase: languageMenuEnglish
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "languageMenuEnglish", "languageMenuEnglish.wav", "press 2 for select English"); 

		// phrase: LangMenuTamil
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "LangMenuTamil", "LangMenuTamil.wav", "Thamilukku en onttrai aluththavum"); 

		// phrase: tamilSelect
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "tamilSelect", "tamilSelect.wav", "You are select Tamil"); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-FEB-09  02:52:39 PM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(eLibrary.PHRASE_MAP, phraseName));
	}
}
