/**
 * Last generated by Orchestration Designer at: 2023-FEB-07  04:23:03 PM
 */
package english.prompts;

import com.avaya.sce.runtimecommon.SCESession;

public class noInputEntry extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for noInputEntry.
	 */
	public noInputEntry() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2023-FEB-17  10:56:52 AM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("noInputEntry");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

	}
	@Override
	public void updatePrompt(SCESession mySession) {
		super.updatePrompt(mySession);
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("noInputEntry");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		setTimeout(1,8000);
		setBargin(1,true);

		add(1, new com.avaya.sce.runtime.PhraseVariableElement("AudioPath:NoInput",
				com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
		
		setTimeout(3,8000);
		setBargin(3,true);

		add(1, new com.avaya.sce.runtime.PhraseVariableElement("AudioPath:NoinputExceed",
				com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
	}
}
