/**
 * Last generated by Orchestration Designer at: 2023-FEB-07  04:26:22 PM
 */
package english.prompts;

import com.avaya.sce.runtimecommon.SCESession;

public class noMatchEntry extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for noMatchEntry.
	 */
	public noMatchEntry() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2023-FEB-07  04:26:22 PM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("noMatchEntry");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

	}
	@Override
	public void updatePrompt(SCESession mySession) {
		super.updatePrompt(mySession);
		add(1, new com.avaya.sce.runtime.PhraseVariableElement("AudioPath:NoMatch",
				com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
	}
}
