package flow.subflow.CartMenuFlow;

import java.util.Collection;
import java.util.LinkedList;
import java.util.List;

import org.json.JSONObject;

import com.avaya.sce.runtime.Prompt;
import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.IVariableField;
import com.avaya.sce.runtimecommon.SCESession;

import connectivity.ws.operations.IntegrationClass;
import connectivity.ws.operations.ProjectVariablesMenuClass;
import flow.IProjectVariables;

/**
 * Class that represents a form.  A form can contain prompts, fields  and links
 * as well as handlers for various events that may occur while the form is executing
 * Last generated by Orchestration Designer at: 2023-JAN-05  10:54:02 AM
 */
public class cartDataAnnounce extends com.avaya.sce.runtime.Form {
	List<String> books = new LinkedList();
	List<String> prices = new LinkedList();
	List<String> quantities = new LinkedList();
	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2023-JAN-05  10:54:02 AM
	 */
	public cartDataAnnounce() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		setNeedsDefaultDisconnectHandler(false);
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method is generated automatically and should not be manually edited.
	 * To manually edit the links for the node, override:
	 *     void updateLinks(Collection links, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2023-FEB-14  12:19:16 PM
	 * @return a collection of links
	 */
	public java.util.Collection getLinks(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Link link;
		java.util.List list;
		java.util.Collection grammarInfo = null;
		java.util.Collection<com.avaya.sce.runtime.CaptureExpression> captureExpr = null;
		// This item does not have any defined links
		list = new java.util.ArrayList();
		String ___tempGrammarName = null;

		return(list);
	}
	/**
	 * This method is generated automatically and should not be manually edited.
	 * To manually edit the properties for the node, override:
	 *     void updateProperties(Collection properties, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2023-FEB-14  12:19:16 PM
	 * @return a collection of properties
	 */
	public java.util.Collection getProperties(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Property property;
		java.util.List list;
		// This item does not have any defined properties
		list = new java.util.ArrayList();

		return(list);
	}
	/**
	 * This method is generated automatically and should not be manually edited.
	 * To manually edit the event handlers for the node, override:
	 *    void updateEvents(Collection events, SCESession mySession)
	 * Last generated by Orchestration Designer at: 2023-FEB-14  12:19:16 PM
	 * @return a collection of Events
	 */
	public java.util.Collection getEvents(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list;
		com.avaya.sce.runtime.Event event;
		list = new java.util.ArrayList();
		java.util.List eventPromptNames = null;
		String ___tempPromptName = null;
		return(list);
	}
	/**
	 * Builds the list of fields for the form.  This list is built
	 * by the code generator based on items in the call flow editor.
	 * This method should not be manually edited as changes may be
	 * overwritten by the code generator.  <br>
	 * To update the fields for the form, override
	 *     public void updateFields(Collection fields, com.avaya.sce.runtimecommon.SCESession mySession)
	 * Last generated by Orchestration Designer at: 2023-FEB-14  12:19:16 PM
	 */
	public java.util.Collection getFields(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		java.util.List promptNames = null;
		java.util.List eventPromptNames = null;
		java.util.List grammarInfo = null;
		java.util.List events = null;
		java.util.List properties = null;
		com.avaya.sce.runtime.Field field = null;
		com.avaya.sce.runtime.Event event = null;
		com.avaya.sce.runtime.Property property = null;
		String ___tempPromptName = null;
		String ___tempGrammarName = null;

		int nbest = 0;

		// Form has no fields associated
		list = new java.util.ArrayList();

		return(list);
	}
	/**
	 * Builds the list of prompts that are used by this flow item<br>
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of prompts for the flow item, override:
	 *     updatePrompts(Collection prompts, SCESession mySession)
	 * @return list of prompts for the menu
	 * Last generated by Orchestration Designer at: 2023-FEB-14  12:19:16 PM
	 */
	public java.util.Collection getPrompts(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		String ___tempPromptName = null;
		// Item has no prompts associated
		list = new java.util.ArrayList();

		return(list);
	}
	/**
	 * Returns the submit item that identifies the next form to transition to.
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-FEB-14  12:19:16 PM
	 */
	public com.avaya.sce.runtime.Submit getSubmit(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Submit submit = null;
		submit = new com.avaya.sce.runtime.Submit("CartMenuFlow-cartOptionsMenu");
		return submit;
	}
	/**
	 * Returns the record item for the form.
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-FEB-14  12:19:16 PM
	 */
	public com.avaya.sce.runtime.Record getRecord(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Record record = null;
		java.util.Collection events = null;
		java.util.Collection promptNames = null;
		java.util.Collection eventPromptNames = null;
		java.util.Collection grammarInfo = null;
		com.avaya.sce.runtime.Event event = null;
		return record;
	}
	/**
	 * Returns the transfer item for the form.
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-FEB-14  12:19:16 PM
	 */
	public com.avaya.sce.runtime.Transfer getTransfer(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Transfer transfer = null;
		return transfer;
	}
	/**
	 * Returns a Throw object that will throw an event at runtime if set.
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-FEB-14  12:19:16 PM
	 */
	public com.avaya.sce.runtime.Throw getThrow(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Throw event = null;
		return event;
	}
	/**
	 * Builds the list of tracking items that are generated by this flow item<br>
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 * @return list of tracking items for the item
	 * Last generated by Orchestration Designer at: 2023-FEB-14  12:19:16 PM
	 */
	public java.util.Collection getTrackingActions(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;

		// Item has no tracking items.
		list = new java.util.ArrayList();
		return(list);
	}
	/**
	 * Returns a collection of platform objects, or extensions to VXML.
	 * These objects result in the generation of the VXML object tag that
	 * the VXML platform attempts to use to load the runtime library that implements
	 * the extension.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-FEB-14  12:19:16 PM
	 */
	public java.util.Collection getPlatformObjects(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.Collection objectList = null;
		java.util.Collection promptNames = null;
		com.avaya.sce.runtime.PlatformObject platformObject = null;

		// Form has no extension objects defined
		objectList = new java.util.ArrayList();
		return(objectList);
	}
	/**
	 * Builds the initial element for the form.  This method is built
	 * by the code generator based on items in the call flow editor.
	 * This method should not be manually edited as changes may be
	 * overwritten by the code generator.  <br>Last generated by Orchestration Designer at: 2023-FEB-14  12:19:16 PM
	 */
	public com.avaya.sce.runtime.Initial getInitial(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Initial initial = null;
		java.util.List promptNames = null;
		java.util.List eventPromptNames = null;
		java.util.List events = null;
		com.avaya.sce.runtime.Event event = null;
		return initial;
	}
	/**
	 * Builds the grammar elements for the form.  This method is built
	 * by the code generator based on items in the call flow editor.
	 * This method should not be manually edited as changes may be
	 * overwritten by the code generator.  <br>Last generated by Orchestration Designer at: 2023-FEB-14  12:19:16 PM
	 */
	public java.util.Collection getGrammars(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List grammarInfo = null;
		grammarInfo = new java.util.ArrayList();

		return grammarInfo;
	}
	@Override
	public void requestBegin(SCESession mySession) {
		try {
			mySession.getVariableField(IProjectVariables.DATA_ELIBRARY,
					IProjectVariables.DATA_ELIBRARY_FIELD_EXIT_LOCATION).setValue("cart data announcement");
			int userId = mySession.getVariableField(IProjectVariables.USER_ID,
					IProjectVariables.USER_ID_FIELD_VALUE).getIntValue();
			IntegrationClass integration = new IntegrationClass();
			String categoryName = mySession
					.getVariableField(IProjectVariables.MENU_COMMON, IProjectVariables.MENU_COMMON_FIELD_CATEGORY_NAME)
					.getStringValue();
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "http://172.16.12.123:8082/cart/cartview/"+userId, mySession);
			List<JSONObject> apiGet = integration.apiGet("http://172.16.12.123:8082/cart/cartview/"+userId,mySession);
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, apiGet.toString(), mySession);
			for (int i = 0; i < apiGet.size(); i++) {
				books.add(apiGet.get(i).get("book").toString());
				quantities.add(apiGet.get(i).get("quantity").toString());
				prices.add(apiGet.get(i).get("price").toString());
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, apiGet.get(i).get("book").toString(), mySession);
			}
			IVariableField booksList = mySession.getVariableField(IProjectVariables.MENU_COMMON,
					IProjectVariables.MENU_COMMON_FIELD_BOOK_MENU_LIST);
			IVariableField priceList = mySession.getVariableField(IProjectVariables.MENU_COMMON,
					IProjectVariables.MENU_COMMON_FIELD_PRICE_LIST);
			IVariableField quantityList = mySession.getVariableField(IProjectVariables.MENU_COMMON,
					IProjectVariables.MENU_COMMON_FIELD_QUANTITY_LIST);
			booksList.setValue(books);
			priceList.setValue(prices);
			quantityList.setValue(quantities);
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, apiGet.toString(), mySession);
		} catch (Exception e) {
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR, e, mySession);
		}
	}

	@Override
	public void updatePrompts(Collection prompts, SCESession mySession) {
		try {
			super.updatePrompts(prompts, mySession);
			Prompt p = new Prompt() {
				@Override
				public void buildPrompt() {

				}
			};
			p.setSession(mySession);
			p.setOrder(com.avaya.sce.runtime.Prompt.STANDARD);
			p.setTimeout(1, 8000);
			p.setBargin(1, true);
			com.avaya.sce.runtime.Format format = null;
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "update promt Entry", mySession);
			int MenuPageNumber = mySession
					.getVariableField(IProjectVariables.MENU_COMMON, IProjectVariables.MENU_COMMON_FIELD_MENU_PAGE)
					.getIntValue();
			int pageCount = 0;
			if (books.size() % 6 == 0) {
				pageCount = books.size() / 6;
			} else {
				pageCount = (books.size() / 6) + 1;
			}
			ProjectVariablesMenuClass setValue = new ProjectVariablesMenuClass();
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "booksMenuPageNumber :" + MenuPageNumber + "\npageCount :"
					+ pageCount + "\nbookSize :" + books.size(), mySession);
			if (pageCount == 1) {
				for (int i = 0; i < books.size(); i++) {
					setValue.projectVariableSetValue(mySession, "http://172.16.12.123:8090/Audiopromts/Elibrary/"
							+ books.get(i).replaceAll(" ", "") + ".wav", i + 1);
					setValue.priceSetValue(mySession, prices.get(i), i+1);
					setValue.quantitySetValue(mySession, quantities.get(i), i+1);
					p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:menuOptionValue" + (i + 1),
							com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
					p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:price",
							com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
					format = new com.avaya.sce.runtime.Format();
					format.add("format", "currency");
					format.add("Currency Format", "N$");
					p.add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,
							"menuCommon:priceValue" + (i + 1), format, false));
					p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:Quantity",
							com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
					format = new com.avaya.sce.runtime.Format();
					format.add("format","number");
					format.add("Number Type","integer");
					format.add("inflection","Nn");
					p.add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,
							"menuCommon:quantityValue" + (i + 1), format, false));
				}
				p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:menuOption9",
						com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
				TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "menuCommon:menuOption9", mySession);
			} else {
				if (MenuPageNumber == 0) {
					for (int i = 0; i < 6; i++) {
						setValue.projectVariableSetValue(mySession, "http://172.16.12.123:8090/Audiopromts/Elibrary/"
								+ books.get(i).replaceAll(" ", "") + ".wav", i + 1);
						setValue.priceSetValue(mySession, prices.get(i), i+1);
						setValue.quantitySetValue(mySession, quantities.get(i), i+1);
						p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:menuOptionValue" + (i + 1),
								com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
						p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:price",
								com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
						format = new com.avaya.sce.runtime.Format();
						format.add("format", "currency");
						format.add("Currency Format", "N$");
						p.add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,
								"menuCommon:priceValue" + (i + 1), format, false));
						p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:Quantity",
								com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
						format = new com.avaya.sce.runtime.Format();
						format.add("format","number");
						format.add("Number Type","integer");
						format.add("inflection","Nn");
						p.add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,
								"menuCommon:quantityValue" + (i + 1), format, false));
					}
					p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:menuOption7",
							com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
					p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:menuOption9",
							com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
				} else if (MenuPageNumber == pageCount - 1) {
					for (int i = MenuPageNumber * 6; i < books.size(); i++) {
						setValue.projectVariableSetValue(mySession, "http://172.16.12.123:8090/Audiopromts/Elibrary/"
								+ books.get(i).replaceAll(" ", "") + ".wav", (i - ((MenuPageNumber * 6) - 1)));
						setValue.priceSetValue(mySession, prices.get(i),(i - ((MenuPageNumber * 6) - 1)));
						setValue.quantitySetValue(mySession, quantities.get(i),(i - ((MenuPageNumber * 6) - 1)));
						p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:menuOptionValue" + (i - ((MenuPageNumber * 6) - 1)),
								com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
						p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:price",
								com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
						format = new com.avaya.sce.runtime.Format();
						format.add("format", "currency");
						format.add("Currency Format", "N$");
						p.add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,
								"menuCommon:priceValue" + (i - ((MenuPageNumber * 6) - 1)), format, false));
						p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:Quantity",
								com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
						format = new com.avaya.sce.runtime.Format();
						format.add("format","number");
						format.add("Number Type","integer");
						format.add("inflection","Nn");
						p.add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,
								"menuCommon:quantityValue" + (i - ((MenuPageNumber * 6) - 1)), format, false));
					}
					p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:menuOption9",
							com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
					p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:menuOption8",
							com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
				} else {
					for (int i = MenuPageNumber * 6; i < (MenuPageNumber * 6) + 6; i++) {
						setValue.projectVariableSetValue(mySession, "http://172.16.12.123:8090/Audiopromts/Elibrary/"
								+ books.get(i).replaceAll(" ", "") + ".wav", (i - ((MenuPageNumber * 6) - 1)));
						setValue.priceSetValue(mySession, prices.get(i),(i - ((MenuPageNumber * 6) - 1)));
						setValue.quantitySetValue(mySession, quantities.get(i),(i - ((MenuPageNumber * 6) - 1)));
						p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:menuOptionValue" + (i - ((MenuPageNumber * 6) - 1)),
								com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
						p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:price",
								com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
						format = new com.avaya.sce.runtime.Format();
						format.add("format", "currency");
						format.add("Currency Format", "N$");
						p.add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,
								"menuCommon:priceValue" + (i - ((MenuPageNumber * 6) - 1)), format, false));
						p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:Quantity",
								com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
						format = new com.avaya.sce.runtime.Format();
						format.add("format","number");
						format.add("Number Type","integer");
						format.add("inflection","Nn");
						p.add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_AUDIO,
								"menuCommon:quantityValue" + (i - ((MenuPageNumber * 6) - 1)), format, false));
					}

					p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:menuOption7",
							com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
					p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:menuOption8",
							com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
					p.add(1, new com.avaya.sce.runtime.PhraseVariableElement("menuCommon:menuOption9",
							com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
				}
			}
			prompts.add(p);

			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO, "update promt Exit", mySession);
		} catch (Exception e) {
			TraceInfo.trace(ITraceInfo.TRACE_LEVEL_ERROR, e, mySession);
		}

	}
	}
