/**
 * Last generated by Orchestration Designer at: 2022-DEC-08  11:17:31 AM
 */
package english.prompts;

public class authorAnnounce extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for authorAnnounce.
	 */
	public authorAnnounce() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2022-DEC-09  10:50:53 AM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("authorAnnounce");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,false);

			if ( new com.avaya.sce.runtime.Condition( "condition", "authorMenu:value", com.avaya.sce.runtime.Expression.STRING_EQUAL, "1", false, null ).evaluate(getSession()) == true ) {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.TEXT,"You are select Jhumpa Lahiri books", null));
			}
			else if ( new com.avaya.sce.runtime.Condition( "condition", "authorMenu:value", com.avaya.sce.runtime.Expression.STRING_EQUAL, "2", false, null ).evaluate(getSession()) == true ) {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.TEXT,"You are select R. Giridharan books", null));
			}
			else if ( new com.avaya.sce.runtime.Condition( "condition", "authorMenu:value", com.avaya.sce.runtime.Expression.STRING_EQUAL, "3", false, null ).evaluate(getSession()) == true ) {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.TEXT,"You are select Priyanka Chopra Jonas books", null));
			}
			else if ( new com.avaya.sce.runtime.Condition( "condition", "authorMenu:value", com.avaya.sce.runtime.Expression.STRING_EQUAL, "4", false, null ).evaluate(getSession()) == true ) {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.TEXT,"You are select Ashwiny Iyer Tiwari books", null));
			}
			else if ( new com.avaya.sce.runtime.Condition( "condition", "authorMenu:value", com.avaya.sce.runtime.Expression.STRING_EQUAL, "5", false, null ).evaluate(getSession()) == true ) {
				add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.TEXT,"You are select Olga Tokarczuk books", null));
			}

	}
}
